languages:
  en:
    punctuation: ["?"]
    content_words: ["what", "who", "where", "when", "why", "how", "which"]
    auxiliaries: true
  fi:
    punctuation: ["?"]
    content_words: ["mikä", "mitä", "missä", "mistä", "mihin", "milloin", "miksi", "kuka", "ketkä", "kumpi", "kuinka", "miten", "montako"]
  ko:
    punctuation: ["?"]
    content_words: ["무엇", "뭐", "어디", "언제", "누구", "왜", "어떻게", "무슨", "어느", "몇"]

extraction:
  min_tokens: 3
  max_tokens: 40
  exclude_fragmentary: true

output:
  format: "conllu"
  separate_by_type: true

