configs:
- config_name: base
  splits:
  - file: tydi_train_base.csv
    split_name: train
  - file: ud_test_base.csv
    split_name: test
- config_name: ablation_no_avg_links_len
  splits:
  - file: tydi_train_ablation_no_avg_links_len.csv
    split_name: train
  - file: ud_test_ablation_no_avg_links_len.csv
    split_name: test
- config_name: ablation_no_avg_max_depth
  splits:
  - file: tydi_train_ablation_no_avg_max_depth.csv
    split_name: train
  - file: ud_test_ablation_no_avg_max_depth.csv
    split_name: test
- config_name: ablation_no_avg_subordinate_chain_len
  splits:
  - file: tydi_train_ablation_no_avg_subordinate_chain_len.csv
    split_name: train
  - file: ud_test_ablation_no_avg_subordinate_chain_len.csv
    split_name: test
- config_name: ablation_no_avg_verb_edges
  splits:
  - file: tydi_train_ablation_no_avg_verb_edges.csv
    split_name: train
  - file: ud_test_ablation_no_avg_verb_edges.csv
    split_name: test
- config_name: ablation_no_lexical_density
  splits:
  - file: tydi_train_ablation_no_lexical_density.csv
    split_name: train
  - file: ud_test_ablation_no_lexical_density.csv
    split_name: test
- config_name: ablation_no_n_tokens
  splits:
  - file: tydi_train_ablation_no_n_tokens.csv
    split_name: train
  - file: ud_test_ablation_no_n_tokens.csv
    split_name: test
- config_name: ablation_no_subordinate_proposition_dist
  splits:
  - file: tydi_train_ablation_no_subordinate_proposition_dist.csv
    split_name: train
  - file: ud_test_ablation_no_subordinate_proposition_dist.csv
    split_name: test
- config_name: ablation_no_verbal_head_per_sent
  splits:
  - file: tydi_train_ablation_no_verbal_head_per_sent.csv
    split_name: train
  - file: ud_test_ablation_no_verbal_head_per_sent.csv
    split_name: test
