# configs/model/glot500_finetune.yaml
model_type: "lm_probe"
lm_name: "cis-lmu/glot500-base"
dropout: 0.1
freeze_model: false
finetune: true
layer_wise: false
layer_index: -1
num_outputs: 1
probe_hidden_size: 96  