wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.21
    cli_version: 0.19.9
    framework: xgboost
    huggingface_version: 4.35.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1743959134
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      - 50
      - 51
      - 53
      - 55
      3:
      - 4
      - 13
      - 15
      - 16
      - 23
      - 42
      - 55
      4: 3.9.21
      5: 0.19.9
      6: 4.35.2
      8:
      - 5
      13: linux-x86_64
experiment:
  desc: null
  value:
    type: lm_probe
    task: n_tokens
    language: fi
    languages: null
    train_language: null
    eval_language: null
    use_controls: false
    control_index: null
model:
  desc: null
  value:
    model_type: lm_probe
    lm_name: cis-lmu/glot500-base
    dropout: 0.3
    freeze_model: false
    layer_wise: false
    layer_index: -1
    num_outputs: 1
training:
  desc: null
  value:
    task_type: regression
    batch_size: 16
    num_epochs: 10
    lr: 1.0e-05
    weight_decay: 0.01
    patience: 3
    scheduler_factor: 0.5
    scheduler_patience: 2
    random_state: 42
    num_workers: 4
data:
  desc: null
  value:
    dataset_name: rokokot/question-type-and-complexity
    cache_dir: /data/leuven/371/vsc37132/qtype-eval/data/cache
    vectors_dir: ./data/features
    languages:
    - fi
    train_language: null
    eval_language: null
seed:
  desc: null
  value: 42
